from service import importer

from octopus.core import initialise
initialise()

importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK Royal Holloway.csv", "Royal Holloway")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of Leeds.csv" , "University of Leeds")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK Durham University.csv", "Durham University")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK Swansea University.csv", "Swansea University")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of Manchester.csv", "University of Manchester")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK Lancaster University.csv", "Lancaster University")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK UCL.csv", "UCL")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of Southampton.csv", "University of Southampton")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK LSE.csv", "LSE")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of Bristol.csv", "University of Bristol")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of St Andrews.csv", "University of St Andrews")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK Queens University Belfast.csv", "Queens University Belfast")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/RCUK University of Edinburgh.csv", "University of Edinburgh")

# New APC batch
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2013-Sheffield.csv", "University of Sheffield")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Bangor.csv", "University of Bangor")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Bath.csv", "University of Bath")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Birmingham.csv", "University of Birmingham")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Bristol.csv", "University of Bristol")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Cranfield.csv", "Cranfield University")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Durham.csv", "Durham University")
# importer.do_import("/home/richard/Dropbox/Documents/OA Monitor/apcdata/APC-data-collection-2014-Glasgow.csv", "University of Glasgow")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Imperial.csv", "Imperial College London")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Lancaster.csv", "University of Lancaster")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Leicester.csv", "University of Leicester")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Plymouth.csv", "University of Plymouth")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-QueenMary-public.csv", "QMU")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-RoyalHolloway.csv", "Royal Holloway")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Sheffield.csv", "University of Sheffield")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Sussex.csv", "University of Sussex")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Swansea.csv", "University of Swansea")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-UCL.csv", "UCL")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-2014-Warwick.csv", "University of Warwick")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-Bristol-1August-9December-2014.csv", "University of Bristol")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-Cardiff-Nov2014.csv", "University of Cardiff")
importer.do_import("/home/richard/Dropbox/Projects/OA Monitor/apcdata/APC-data-collection-Manchester-20141223.csv", "University of Manchester")
