python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK Royal Holloway.csv" -i "Royal Holloway"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of Leeds.csv" -i "University of Leeds"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK Durham University.csv" -i "Durham University"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK Swansea University.csv" -i "Swansea University"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of Manchester.csv" -i "University of Manchester"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK Lancaster University.csv" -i "Lancaster University"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK UCL.csv" -i "UCL"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of Southampton.csv" -i "University of Southampton"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK LSE.csv" -i "LSE"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of Bristol.csv" -i "University of Bristol"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of St Andrews.csv" -i "University of St Andrews"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK Queens University Belfast.csv" -i "Queens University Belfast"
python service/scripts/importcsv.py -s "/home/richard/Dropbox/Documents/OA Monitor/apcdata/RCUK University of Edinburgh.csv" -i "University of Edinburgh"
